INSERT INTO `language` (`id`, `code`, `name`) VALUES (1, 'ab', 'Abkhaz');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (2, 'aa', 'Afar');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (3, 'af', 'Afrikaans');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (4, 'ak', 'Akan');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (5, 'sq', 'Albanian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (6, 'am', 'Amharic');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (7, 'ar', 'Arabic');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (8, 'an', 'Aragonese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (9, 'hy', 'Armenian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (10, 'as', 'Assamese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (11, 'av', 'Avaric');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (12, 'ae', 'Avestan');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (13, 'ay', 'Aymara');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (14, 'az', 'Azerbaijani');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (15, 'bm', 'Bambara');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (16, 'ba', 'Bashkir');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (17, 'eu', 'Basque');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (18, 'be', 'Belarusian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (19, 'bn', 'Bengali; Bangla');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (20, 'bh', 'Bihari');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (21, 'bi', 'Bislama');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (22, 'bs', 'Bosnian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (23, 'br', 'Breton');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (24, 'bg', 'Bulgarian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (25, 'my', 'Burmese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (26, 'ca', 'Catalan; Valencian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (27, 'ch', 'Chamorro');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (28, 'ce', 'Chechen');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (29, 'ny', 'Chichewa; Chewa; Nyanja');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (30, 'zh', 'Chinese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (31, 'cv', 'Chuvash');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (32, 'kw', 'Cornish');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (33, 'co', 'Corsican');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (34, 'cr', 'Cree');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (35, 'hr', 'Croatian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (36, 'cs', 'Czech');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (37, 'da', 'Danish');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (38, 'dv', 'Divehi; Dhivehi; Maldivian;');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (39, 'nl', 'Dutch');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (40, 'dz', 'Dzongkha');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (41, 'en', 'English');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (42, 'eo', 'Esperanto');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (43, 'et', 'Estonian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (44, 'ee', 'Ewe');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (45, 'fo', 'Faroese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (46, 'fj', 'Fijian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (47, 'fi', 'Finnish');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (48, 'fr', 'French');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (49, 'ff', 'Fula; Fulah; Pulaar; Pular');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (50, 'gl', 'Galician');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (51, 'ka', 'Georgian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (52, 'de', 'German');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (53, 'el', 'Greek, Modern');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (54, 'gn', 'GuaranÃ­');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (55, 'gu', 'Gujarati');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (56, 'ht', 'Haitian; Haitian Creole');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (57, 'ha', 'Hausa');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (58, 'he', 'Hebrew (modern)');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (59, 'hz', 'Herero');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (60, 'hi', 'Hindi');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (61, 'ho', 'Hiri Motu');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (62, 'hu', 'Hungarian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (63, 'ia', 'Interlingua');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (64, 'id', 'Indonesian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (65, 'ie', 'Interlingue');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (66, 'ga', 'Irish');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (67, 'ig', 'Igbo');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (68, 'ik', 'Inupiaq');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (69, 'io', 'Ido');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (70, 'is', 'Icelandic');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (71, 'it', 'Italian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (72, 'iu', 'Inuktitut');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (73, 'ja', 'Japanese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (74, 'jv', 'Javanese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (75, 'kl', 'Kalaallisut, Greenlandic');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (76, 'kn', 'Kannada');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (77, 'kr', 'Kanuri');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (78, 'ks', 'Kashmiri');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (79, 'kk', 'Kazakh');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (80, 'km', 'Khmer');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (81, 'ki', 'Kikuyu, Gikuyu');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (82, 'rw', 'Kinyarwanda');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (83, 'ky', 'Kyrgyz');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (84, 'kv', 'Komi');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (85, 'kg', 'Kongo');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (86, 'ko', 'Korean');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (87, 'ku', 'Kurdish');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (88, 'kj', 'Kwanyama, Kuanyama');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (89, 'la', 'Latin');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (90, 'lb', 'Luxembourgish, Letzeburgesch');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (91, 'lg', 'Ganda');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (92, 'li', 'Limburgish, Limburgan, Limburger');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (93, 'ln', 'Lingala');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (94, 'lo', 'Lao');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (95, 'lt', 'Lithuanian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (96, 'lu', 'Luba-Katanga');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (97, 'lv', 'Latvian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (98, 'gv', 'Manx');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (99, 'mk', 'Macedonian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (100, 'mg', 'Malagasy');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (101, 'ms', 'Malay');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (102, 'ml', 'Malayalam');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (103, 'mt', 'Maltese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (104, 'mi', 'MÄori');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (105, 'mr', 'Marathi (MarÄá¹­hÄ«)');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (106, 'mh', 'Marshallese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (107, 'mn', 'Mongolian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (108, 'na', 'Nauru');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (109, 'nv', 'Navajo, Navaho');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (110, 'nb', 'Norwegian BokmÃ¥l');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (111, 'nd', 'North Ndebele');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (112, 'ne', 'Nepali');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (113, 'ng', 'Ndonga');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (114, 'nn', 'Norwegian Nynorsk');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (115, 'no', 'Norwegian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (116, 'ii', 'Nuosu');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (117, 'nr', 'South Ndebele');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (118, 'oc', 'Occitan');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (119, 'oj', 'Ojibwe, Ojibwa');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (120, 'cu', 'Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (121, 'om', 'Oromo');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (122, 'or', 'Oriya');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (123, 'os', 'Ossetian, Ossetic');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (124, 'pa', 'Panjabi, Punjabi');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (125, 'pi', 'PÄli');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (126, 'fa', 'Persian (Farsi)');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (127, 'pl', 'Polish');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (128, 'ps', 'Pashto, Pushto');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (129, 'pt', 'Portuguese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (130, 'qu', 'Quechua');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (131, 'rm', 'Romansh');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (132, 'rn', 'Kirundi');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (133, 'ro', 'Romanian, [])');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (134, 'ru', 'Russian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (135, 'sa', 'Sanskrit (Saá¹ská¹›ta)');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (136, 'sc', 'Sardinian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (137, 'sd', 'Sindhi');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (138, 'se', 'Northern Sami');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (139, 'sm', 'Samoan');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (140, 'sg', 'Sango');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (141, 'sr', 'Serbian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (142, 'gd', 'Scottish Gaelic; Gaelic');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (143, 'sn', 'Shona');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (144, 'si', 'Sinhala, Sinhalese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (145, 'sk', 'Slovak');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (146, 'sl', 'Slovene');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (147, 'so', 'Somali');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (148, 'st', 'Southern Sotho');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (149, 'es', 'Spanish; Castilian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (150, 'su', 'Sundanese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (151, 'sw', 'Swahili');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (152, 'ss', 'Swati');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (153, 'sv', 'Swedish');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (154, 'ta', 'Tamil');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (155, 'te', 'Telugu');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (156, 'tg', 'Tajik');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (157, 'th', 'Thai');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (158, 'ti', 'Tigrinya');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (159, 'bo', 'Tibetan Standard, Tibetan, Central');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (160, 'tk', 'Turkmen');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (161, 'tl', 'Tagalog');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (162, 'tn', 'Tswana');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (163, 'to', 'Tonga (Tonga Islands)');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (164, 'tr', 'Turkish');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (165, 'ts', 'Tsonga');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (166, 'tt', 'Tatar');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (167, 'tw', 'Twi');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (168, 'ty', 'Tahitian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (169, 'ug', 'Uyghur, Uighur');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (170, 'uk', 'Ukrainian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (171, 'ur', 'Urdu');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (172, 'uz', 'Uzbek');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (173, 've', 'Venda');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (174, 'vi', 'Vietnamese');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (175, 'vo', 'VolapÃ¼k');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (176, 'wa', 'Walloon');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (177, 'cy', 'Welsh');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (178, 'wo', 'Wolof');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (179, 'fy', 'Western Frisian');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (180, 'xh', 'Xhosa');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (181, 'yi', 'Yiddish');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (182, 'yo', 'Yoruba');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (183, 'za', 'Zhuang, Chuang');
INSERT INTO `language` (`id`, `code`, `name`) VALUES (184, 'zu', 'Zulu');
